// One-shot seed for the Resources directory: adds Capital Region and
// Central New York entries researched 2026-04. Idempotent — skips any
// row whose Resource+Chapter pair already exists in Firestore.
//
// Run: cd functions && node scripts/seedResourcesCapRegCny.js
//
// Requires Application Default Credentials with write access to the
// gnf-app-9d7e3 project (same auth used by scripts/dumpResources.js).
const admin = require("firebase-admin");

admin.initializeApp({ projectId: "gnf-app-9d7e3" });
const db = admin.firestore();

const RESOURCES = [
  // -------------------- Capital Region --------------------
  {
    Resource: "Tech Valley Center of Gravity",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "Hardware, makerspace, light manufacturing",
    CountiesServed: "Rensselaer, Albany, Saratoga",
    Website: "https://www.tvcog.net",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "10,000+ sq ft makerspace in downtown Troy with 3D printing, laser cutting, electronics, welding, wood and metal shops. Membership grants 24/7 shop access and classes. Houses a NYS-certified Manufacturing Incubator (16V) for hardware founders bringing physical products to market.",
  },
  {
    Resource: "RPI Severino Center for Technological Entrepreneurship",
    Type: "Education",
    Stage: "Ideation",
    Chapter: "Capital Region",
    FocusArea: "Tech entrepreneurship, RPI students and alumni",
    CountiesServed: "Rensselaer, Albany",
    Website: "https://lallyschool.rpi.edu/severino-center",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Lally School of Management center at RPI. Runs the Change the World Challenge ($1K idea prizes), the Severino Pitch Competition, and entrepreneurship coursework. Founders get pitch coaching, small prize money, and intros to RPI alumni investors.",
  },
  {
    Resource: "Rensselaer Center for Open Source (RCOS)",
    Type: "Incubator/Accelerator",
    Stage: "Ideation",
    Chapter: "Capital Region",
    FocusArea: "Open source software, student founders",
    CountiesServed: "Rensselaer",
    Website: "https://rcos.io",
    AverageCheckSize: "Stipend",
    RelocationRequired: "No",
    About: "RPI program where students build open source projects for academic credit or paid stipends. Provides a structured semester, faculty and alumni mentors, and a public showcase. Useful entry point for technical student founders in Troy.",
  },
  {
    Resource: "UAlbany Innovation Center",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "Tech startups, university spinouts",
    CountiesServed: "Albany",
    Website: "https://www.albany.edu/research-economic-development/entrepreneurship-innovation/incubator",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Wet-lab and dry-office incubator on UAlbany's campus operated by the Office for Innovation Development & Commercialization. Tenants get below-market space, shared equipment, and IP/faculty support. Used by life science, AI, and atmospheric sensing spinouts.",
  },
  {
    Resource: "UAlbany Bioscience Development Corp (UABDC)",
    Type: "Incubator/Accelerator",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Biotech, life sciences wet lab",
    CountiesServed: "Albany",
    Website: "https://www.uabdc.org",
    AverageCheckSize: "NA",
    RelocationRequired: "Yes",
    About: "80-acre Health Sciences campus with 500,000+ sq ft of lab, office, and shared space owned by the University at Albany. Leases scalable wet-lab and office space to biotech startups co-located with UAlbany Health Sciences faculty.",
  },
  {
    Resource: "Albany NanoTech Complex Incubator",
    Type: "Incubator/Accelerator",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Semiconductors, nanotech, photonics",
    CountiesServed: "Albany",
    Website: "https://albanynanotech.com",
    AverageCheckSize: "NA",
    RelocationRequired: "Yes",
    About: "NY CREATES-operated cleanroom complex on Fuller Road. Startups can buy time on 300mm tools, co-locate engineers near IBM and Tokyo Electron, and tap the National Semiconductor Technology Center hub. Capital intensive; for funded chip and photonics companies.",
  },
  {
    Resource: "NSTC Albany Hub (Natcast)",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Semiconductor commercialization, federal CHIPS programs",
    CountiesServed: "Albany",
    Website: "https://natcast.org",
    AverageCheckSize: "$500K-$5M",
    RelocationRequired: "Yes",
    About: "Natcast operates the federal National Semiconductor Technology Center extreme ultraviolet (EUV) accelerator at Albany NanoTech. Funds prototyping, workforce training, and access to advanced lithography for chip startups. For funded semiconductor and photonics companies.",
  },
  {
    Resource: "Union College U-Start",
    Type: "Incubator/Accelerator",
    Stage: "Ideation",
    Chapter: "Capital Region",
    FocusArea: "Student startups, summer accelerator",
    CountiesServed: "Schenectady",
    Website: "https://www.union.edu/entrepreneurship",
    AverageCheckSize: "Stipend",
    RelocationRequired: "No",
    About: "Union College summer entrepreneurship program providing student founders with stipends, on-campus housing, mentorship, and structured demos. Hosted by Union's entrepreneurship program in Schenectady.",
  },
  {
    Resource: "Skidmore Management & Business Entrepreneurship",
    Type: "Education",
    Stage: "Ideation",
    Chapter: "Capital Region",
    FocusArea: "Liberal arts entrepreneurship, student venture",
    CountiesServed: "Saratoga",
    Website: "https://www.skidmore.edu/mbe",
    AverageCheckSize: "Cash prizes",
    RelocationRequired: "No",
    About: "Skidmore's Management & Business department runs the Kenneth A. Freirich Entrepreneurship Competition (cash prizes), entrepreneurship coursework, and venture mentoring for students and recent alumni in Saratoga Springs.",
  },
  {
    Resource: "Eastern New York Angels (ENYA)",
    Type: "Angel Group",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "Seed investment, Tech Valley companies",
    CountiesServed: "11-county Tech Valley region around Albany",
    Website: "https://easternnyangels.com",
    AverageCheckSize: "$100K-$500K",
    RelocationRequired: "No",
    About: "Albany-based managed angel group founded 2010. Provides seed funding to early-stage NY-based companies in biotech, business products, cleantech, energy, nanotech, security, semiconductors and software. Pitches via monthly screening; aggregate checks typically $100K-$500K.",
  },
  {
    Resource: "FreshTracks Capital",
    Type: "Venture Capital",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "Northeast seed/Series A, generalist",
    CountiesServed: "Capital Region, Vermont, Northeast",
    Website: "https://freshtrackscap.com",
    AverageCheckSize: "$500K-$2M",
    RelocationRequired: "No",
    About: "Vermont-based seed fund actively investing across the Capital Region and upstate NY. Generalist with food, consumer, and B2B SaaS portfolio companies. Writes Series Seed and follows on; reachable through ENYA and Upstate Venture Connect.",
  },
  {
    Resource: "Cayuga Venture Fund",
    Type: "Venture Capital",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "Upstate NY tech, life sciences",
    CountiesServed: "Capital Region, Upstate NY",
    Website: "https://cvf.biz",
    AverageCheckSize: "$500K-$2M",
    RelocationRequired: "No",
    About: "Ithaca-based fund operating since 1994 with a mandate covering upstate NY including the Capital Region. Invests in tech and life-sciences seed and Series A. Active syndicate partner with ENYA on Albany-area deals; many portfolio companies have a Cornell tech connection.",
  },
  {
    Resource: "FuzeHub",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Manufacturing connections, NY MEP affiliate",
    CountiesServed: "Statewide (Albany HQ)",
    Website: "https://fuzehub.com",
    AverageCheckSize: "$25K-$100K",
    RelocationRequired: "No",
    About: "Albany-headquartered statewide MEP affiliate that matches manufacturers to engineering resources. Runs the Jeff Lawrence Innovation Fund (commercialization grants up to ~$100K) and $25K Manufacturing Grants. Heavy program activity in the Capital Region.",
  },
  {
    Resource: "Center for Economic Growth (CEG)",
    Type: "Community",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "Regional economic development, Tech Council",
    CountiesServed: "Albany, Rensselaer, Saratoga, Schenectady, Columbia, Greene, Warren, Washington",
    Website: "https://www.ceg.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Albany-based 8-county economic development org. Runs site-selection help, the Tech Council, manufacturing peer groups, and exporter assistance. Founders get warm intros to local employers, IDAs, and ESD; not a check writer.",
  },
  {
    Resource: "SCORE Northeast NY",
    Type: "Mentorship",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "Volunteer mentors, all sectors",
    CountiesServed: "Albany, Rensselaer, Saratoga, Schenectady, Columbia, Greene, Warren, Washington, Fulton, Montgomery",
    Website: "https://northeastny.score.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "SBA-supported volunteer mentor chapter covering 11 Capital Region/Northeast NY counties. Free 1:1 mentoring and free workshops on business plans, financials, and marketing. Mentors are retired and active executives across industries.",
  },
  {
    Resource: "Small Business Development Center at UAlbany",
    Type: "Government",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "Free advising, business plans, financing packaging",
    CountiesServed: "Albany, Rensselaer, Saratoga, Schenectady, Columbia, Greene",
    Website: "https://www.albany.edu/sbdc",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "SBA-funded free advisory center at UAlbany. Founders get one-on-one help with business plans, loan packages, and government contracting. Default first stop for most non-tech Capital Region small businesses.",
  },
  {
    Resource: "SUNY Adirondack SBDC",
    Type: "Government",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "North Country/Adirondack small business advising",
    CountiesServed: "Warren, Washington, northern Saratoga",
    Website: "https://www.sunyacc.edu/sbdc",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "SBDC site at SUNY Adirondack in Queensbury covering the northern Capital Region. Free business plan and financing assistance for founders north of Saratoga. Useful for tourism, hospitality, and main-street operators.",
  },
  {
    Resource: "Capital Region REDC (Empire State Development)",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "State grants via Consolidated Funding Application",
    CountiesServed: "Albany, Rensselaer, Saratoga, Schenectady, Columbia, Greene, Warren, Washington",
    Website: "https://regionalcouncils.ny.gov/capital-region",
    AverageCheckSize: "$50K-$2M+",
    RelocationRequired: "No",
    About: "Capital Region Regional Economic Development Council distributes state grants via the annual CFA process. Companies investing in capital projects, training, or tourism can win matching grants. Strategic plan emphasizes nano, life science, and clean energy.",
  },
  {
    Resource: "Capitalize Albany / Albany IDA",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Real estate incentives, PILOTs, downtown revitalization",
    CountiesServed: "Albany",
    Website: "https://capitalizealbany.com",
    AverageCheckSize: "Varies",
    RelocationRequired: "No",
    About: "City of Albany's IDA and economic development corp. Runs the Amplify Grant program for storefronts and upper-floor housing, IDA tax incentives, and Impact Downtown Albany. For founders opening physical businesses or doing real estate.",
  },
  {
    Resource: "Saratoga County Prosperity Partnership",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Site selection, business attraction",
    CountiesServed: "Saratoga",
    Website: "https://saratogapartnership.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Saratoga County's economic development arm. Runs site selection, IDA coordination, and the GLOBALFOUNDRIES supplier program. Founders relocating to or scaling in Saratoga County get help with sites, permits, and incentive stacking.",
  },
  {
    Resource: "Saratoga County IDA",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "PILOTs, sales/mortgage tax exemptions",
    CountiesServed: "Saratoga",
    Website: "https://saratogacountyida.org",
    AverageCheckSize: "Tax abatement",
    RelocationRequired: "No",
    About: "Industrial Development Agency offering PILOTs, sales-tax exemption on construction materials, and mortgage-tax abatement for qualifying capital projects in Saratoga County. Targeted at manufacturers and large commercial projects, not pre-revenue founders.",
  },
  {
    Resource: "Schenectady Metroplex Development Authority",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Downtown facade and redevelopment grants, IDA",
    CountiesServed: "Schenectady",
    Website: "https://www.schenectadymetroplex.com",
    AverageCheckSize: "$25K-$500K",
    RelocationRequired: "No",
    About: "Schenectady's downtown development authority. Provides facade grants, real estate financing, and incentives for projects in Schenectady, Scotia, and surrounding villages. Active developer of downtown Schenectady; useful for restaurant, retail, and office founders.",
  },
  {
    Resource: "Troy Local Development Corporation",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Microloans, facade grants, downtown Troy",
    CountiesServed: "Rensselaer (Troy)",
    Website: "https://www.troyny.gov/economic-development",
    AverageCheckSize: "$5K-$50K",
    RelocationRequired: "No",
    About: "City of Troy's LDC running storefront improvement grants, small business loans, and the Troy IDA. Geared toward main-street businesses opening in Troy. Loans are typically gap financing alongside a bank.",
  },
  {
    Resource: "Community Loan Fund of the Capital Region",
    Type: "Funding",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "CDFI loans, microloans, small business",
    CountiesServed: "Albany, Rensselaer, Saratoga, Schenectady, Columbia, Greene, Warren, Washington",
    Website: "https://mycommunityloanfund.org",
    AverageCheckSize: "$1K-$250K",
    RelocationRequired: "No",
    About: "Albany-based CDFI lending to small businesses, nonprofits, and affordable-housing developers across 8 counties. Microloans start at $1K; commercial loans go to $250K+. Also runs the Small Business Academy training. The default option for founders banks won't touch.",
  },
  {
    Resource: "Broadview Federal Credit Union — Business Lending",
    Type: "Funding",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "SBA 7(a)/504, credit-union business loans",
    CountiesServed: "Capital Region",
    Website: "https://www.broadviewfcu.com/business",
    AverageCheckSize: "$50K-$5M",
    RelocationRequired: "No",
    About: "Broadview (formed by SEFCU and CAP COM merger) is the largest Capital Region credit union and a top SBA 7(a) and 504 lender locally. Real-estate and equipment financing for established small businesses. Not for pre-revenue.",
  },
  {
    Resource: "Workforce Development Institute (WDI)",
    Type: "Education",
    Stage: "Growth",
    Chapter: "Capital Region",
    FocusArea: "Workforce training grants, manufacturing",
    CountiesServed: "Statewide (Albany HQ)",
    Website: "https://wdiny.org",
    AverageCheckSize: "$5K-$50K",
    RelocationRequired: "No",
    About: "Albany-headquartered nonprofit funding workforce training, training equipment, and child care for working families. Capital Region regional director writes small grants to manufacturers and other employers for skills training.",
  },
  {
    Resource: "HVCC TEC-SMART",
    Type: "Education",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "Clean energy, semiconductor workforce training",
    CountiesServed: "Saratoga, Rensselaer, Albany",
    Website: "https://www.hvcc.edu/tecsmart",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Hudson Valley Community College's Malta campus training center for clean energy, semiconductor, and advanced manufacturing technicians. Founders building hardware/cleantech companies in the GLOBALFOUNDRIES corridor use it as a workforce pipeline and shared training facility.",
  },
  {
    Resource: "SUNY Schenectady Workforce Development",
    Type: "Education",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "Culinary, hospitality, workforce certs",
    CountiesServed: "Schenectady, Albany, Saratoga",
    Website: "https://sunysccc.edu/Academics/School-of-Workforce-Development-Community-Education.html",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Short-term certificates and incumbent-worker training at SUNY Schenectady. Strong culinary and hospitality programs (the college's flagship). Useful for restaurant founders sourcing kitchen staff and small employers needing skills-training grants.",
  },
  {
    Resource: "Tech Valley Game Space",
    Type: "Community",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "Game development community",
    CountiesServed: "Albany, Rensselaer, Saratoga, Schenectady",
    Website: "https://www.tvgs.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Capital Region game-developer nonprofit running monthly meetups, jams, and workshops. Connects indie game founders to peer studios, RPI/Vicarious Visions alumni, and playtesters. Free or low-cost participation.",
  },
  {
    Resource: "Albany Barn / Electric City Barn",
    Type: "Nonprofit",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "Creative entrepreneurs, artist live/work, makerspace",
    CountiesServed: "Albany, Schenectady",
    Website: "https://albanybarn.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Live/work facility for creative entrepreneurs in Albany's Arbor Hill, plus the Electric City Barn makerspace in Schenectady offering affordable studio and class space. Targeted at creative founders, not tech.",
  },
  {
    Resource: "Urban Co-Works",
    Type: "Coworking",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "Coworking, private offices",
    CountiesServed: "Albany, Rensselaer",
    Website: "https://urbancoworks.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Coworking operator with locations in downtown Albany and Troy. Hot desks, dedicated desks, and private offices on month-to-month terms. Used by remote workers and small Capital Region startup teams that don't need a full lease.",
  },
  {
    Resource: "Stack456",
    Type: "Coworking",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "Coworking, downtown Schenectady",
    CountiesServed: "Schenectady",
    Website: "https://stack456.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Coworking and event space at 456 State Street in downtown Schenectady. Day passes, dedicated desks, and meeting rooms. Frequent host of Albany.tech-style meetups and Metroplex-supported events.",
  },
  {
    Resource: "Albany Law School Community Development Clinic",
    Type: "Legal",
    Stage: "Early",
    Chapter: "Capital Region",
    FocusArea: "Free legal help for nonprofits and social enterprises",
    CountiesServed: "Albany, Rensselaer, Saratoga, Schenectady",
    Website: "https://www.albanylaw.edu/experiential-learning/clinical-legal-studies",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Albany Law School clinic where supervised law students provide free legal help to nonprofits, cooperatives, and small social enterprises in the Capital Region. Entity formation, bylaws, contracts, and 501(c)(3) applications.",
  },
  {
    Resource: "Albany.tech",
    Type: "Community",
    Stage: "All",
    Chapter: "Capital Region",
    FocusArea: "Tech meetups, networking",
    CountiesServed: "Albany, Rensselaer, Saratoga, Schenectady",
    Website: "https://albany.tech",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Volunteer-run hub aggregating Capital Region tech meetups, a job board, and a Slack community. Free to join. Where local engineers, founders, and recruiters keep up with what's happening in the regional ecosystem.",
  },

  // -------------------- Central New York --------------------
  {
    Resource: "The Tech Garden",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Tech startups, software, hardware",
    CountiesServed: "Onondaga, Madison, Oswego, Cortland, Cayuga",
    Website: "https://thetechgarden.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "CenterState CEO's downtown Syracuse incubator. Founders get private offices and coworking space, programming including the Tech Garden Pre-Seed program, the GENIUS NY pipeline, and one-on-one coaching. The hub for the CNY tech startup community.",
  },
  {
    Resource: "GENIUS NY",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "UAS, drones, robotics, autonomous systems",
    CountiesServed: "Onondaga, Oneida (Griffiss)",
    Website: "https://geniusny.com",
    AverageCheckSize: "$500K or $1M",
    RelocationRequired: "Yes",
    About: "Year-long accelerator for unmanned systems and autonomous tech run by CenterState CEO and funded by ESD. Five finalists each cohort split $3M ($1M grand prize, four $500K investments). Cohort 9 ran 2025-2026; Cohort 10 applications open. Companies must base operations in CNY.",
  },
  {
    Resource: "Syracuse University Blackstone LaunchPad",
    Type: "Incubator/Accelerator",
    Stage: "Ideation",
    Chapter: "Central New York",
    FocusArea: "Student/alumni startups, all sectors",
    CountiesServed: "Onondaga",
    Website: "https://library.syracuse.edu/blackstonelaunchpad/",
    AverageCheckSize: "Up to $10K",
    RelocationRequired: "No",
    About: "Free entrepreneurship hub inside Bird Library open to all SU students, alumni, and faculty. Coaching, pitch competitions (Impact Prize, Orange Tank), workshops, and connections to the Blackstone national network. Hosts the SU IdeaLink summer accelerator.",
  },
  {
    Resource: "Couri Hatchery (Whitman School)",
    Type: "Incubator/Accelerator",
    Stage: "Ideation",
    Chapter: "Central New York",
    FocusArea: "Student ventures, all sectors",
    CountiesServed: "Onondaga",
    Website: "https://whitman.syr.edu/programs-and-academics/academics/entrepreneurship/couri-hatchery/",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Student business incubator at Syracuse University's Whitman School of Management. Free workspace, mentorship from Whitman faculty and alumni, and structured advising for SU student-founded ventures. Pairs with the Falcone Center for grant access.",
  },
  {
    Resource: "Falcone Center for Entrepreneurship (Whitman)",
    Type: "Education",
    Stage: "Ideation",
    Chapter: "Central New York",
    FocusArea: "Entrepreneurship education, family business",
    CountiesServed: "Onondaga",
    Website: "https://whitman.syr.edu/programs-and-academics/academics/entrepreneurship/",
    AverageCheckSize: "Up to $20K",
    RelocationRequired: "No",
    About: "Syracuse University's flagship entrepreneurship academic center inside the Whitman School. Runs the Panasci Business Plan Competition (up to $20K cash plus in-kind), the Couri Hatchery, EEE/Family Business Center programming, and entrepreneurship majors.",
  },
  {
    Resource: "Le Moyne Madden Center for Entrepreneurship",
    Type: "Education",
    Stage: "Ideation",
    Chapter: "Central New York",
    FocusArea: "Student entrepreneurship, family business",
    CountiesServed: "Onondaga",
    Website: "https://www.lemoyne.edu/madden-school-of-business/madden-center-for-entrepreneurship/",
    AverageCheckSize: "Cash prizes",
    RelocationRequired: "No",
    About: "Le Moyne College's entrepreneurship center inside the Madden School of Business. Runs the annual Le Moyne Pitch Contest with cash prizes, hosts the Family Business Forum, and offers mentorship and curriculum for student founders. Open to Le Moyne students and alumni.",
  },
  {
    Resource: "thINCubator (MVCC)",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Tech startups, Mohawk Valley",
    CountiesServed: "Oneida, Herkimer, Madison",
    Website: "https://thincubator.co",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Mohawk Valley Community College's startup incubator in downtown Utica. Memberships from $150/mo; private offices from $425/mo. Houses the Refinery accelerator, the Mohawk Valley SBDC, the NGIN Equity Incubator Initiative, and a network of mentors and meetups.",
  },
  {
    Resource: "Griffiss Institute",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Cybersecurity, defense tech, federal tech transfer",
    CountiesServed: "Oneida, Herkimer",
    Website: "https://www.griffissinstitute.org",
    AverageCheckSize: "Federal contracts",
    RelocationRequired: "Yes",
    About: "Nonprofit talent and tech-transfer hub at Griffiss Park in Rome, partnered with the Air Force Research Lab Information Directorate. Operates the Innovare Advancement Center with lab space, the VICEROY cyber program, and SBIR/STTR commercialization support for defense-adjacent founders.",
  },
  {
    Resource: "Clarkson Shipley Center for Innovation",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Engineering, hardware, cleantech",
    CountiesServed: "Lewis, North Country",
    Website: "https://www.clarkson.edu/shipley-center-innovation",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Clarkson University's entrepreneurship center supporting student and regional founders. Runs the Reh Center Pitch Competition, the Mickel Endowed Scholar program, and ideation workshops. Provides Clarkson lab access for hardware founders working on prototypes.",
  },
  {
    Resource: "CNY Biotech Accelerator (SUNY Upstate)",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Biotech, medical devices, life sciences",
    CountiesServed: "Onondaga",
    Website: "https://www.upstate.edu/cnybac/",
    AverageCheckSize: "NA",
    RelocationRequired: "Yes",
    About: "Wet-lab incubator on the SUNY Upstate Medical University campus in Syracuse. Provides BSL-2 lab space, shared core equipment, and access to Upstate clinical investigators. Tenants include therapeutics, diagnostics, and medical-device startups; FuzeHub and ESD subsidize lab fees.",
  },
  {
    Resource: "REV: Ithaca Startup Works",
    Type: "Incubator/Accelerator",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Cornell-affiliated startups, hardware, software",
    CountiesServed: "Cortland, Cayuga, Tompkins",
    Website: "https://revithaca.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Cornell-affiliated incubator in downtown Ithaca that pulls founders from southern CNY. Coworking, prototyping space, the Hardware Accelerator program, and direct intros to Cayuga Venture Fund and Excell Partners.",
  },
  {
    Resource: "Cayuga Venture Fund",
    Type: "Venture Capital",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Tech, life sciences, upstate startups",
    CountiesServed: "Onondaga, Cortland, Cayuga, Tompkins, Upstate NY",
    Website: "https://cvf.biz",
    AverageCheckSize: "$500K-$3M",
    RelocationRequired: "No",
    About: "Ithaca-based seed and Series A fund operating since 1994. Invests in upstate NY tech and life sciences, particularly Cornell, Syracuse, and SUNY Upstate spinouts. Many portfolio companies have a strong university tech connection; lead and co-lead checks.",
  },
  {
    Resource: "Seed Capital Fund of CNY",
    Type: "Angel Group",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Early-stage tech, life sciences",
    CountiesServed: "Onondaga, Madison, Oneida, Cayuga, Cortland",
    Website: "https://www.scfcny.com",
    AverageCheckSize: "$50K-$250K",
    RelocationRequired: "No",
    About: "Syracuse-based angel group of accredited CNY investors (~44 members). Invests in high-growth early-stage companies within a 2-hour drive of Syracuse. Founders pitch the membership; checks typically convertible notes or SAFEs and frequently syndicated with Cayuga Venture Fund or Armory Square Ventures.",
  },
  {
    Resource: "Mohawk Valley EDGE",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Central New York",
    FocusArea: "Site selection, manufacturing, semiconductor",
    CountiesServed: "Oneida, Herkimer",
    Website: "https://mvedge.org",
    AverageCheckSize: "Varies",
    RelocationRequired: "Yes",
    About: "Regional economic development corp for Oneida and Herkimer counties. Offers IDA financing, PILOTs, site location at Marcy Nanocenter and Griffiss Park, and attraction packages. Active steward of the Wolfspeed/SUNY Poly chip-fab corridor.",
  },
  {
    Resource: "CenterState CEO",
    Type: "Community",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Regional economic development, chamber",
    CountiesServed: "Onondaga, Madison, Oswego, Cortland, Cayuga, Oneida",
    Website: "https://www.centerstateceo.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "12-county chamber of commerce and economic-development organization for the Syracuse region. Runs The Tech Garden, GENIUS NY, the Up Start business plan competition, the Minority and Women Emerging Entrepreneurs program, and Work Train. Primary entry point for founders into CNY's small business ecosystem.",
  },
  {
    Resource: "40 Below",
    Type: "Community",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Young professional network, civic engagement",
    CountiesServed: "Onondaga, CNY",
    Website: "https://40belowsyracuse.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "CenterState CEO young-professional network for Syracuse-area people under 40. Founders get peer connections, civic-engagement task forces (public arts, urban planning), and pitch-night events. Free to join.",
  },
  {
    Resource: "SCORE Syracuse",
    Type: "Mentorship",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Small business mentorship",
    CountiesServed: "Onondaga, Madison, Oswego, Cortland, Cayuga",
    Website: "https://syracuse.score.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Local chapter of the SBA-backed national mentorship nonprofit. Free 1:1 mentoring sessions with retired and active executives, free workshops on business plans, financing, and marketing. Mentors available remote or at Syracuse-area libraries.",
  },
  {
    Resource: "SCORE Mohawk Valley",
    Type: "Mentorship",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Small business mentorship",
    CountiesServed: "Oneida, Herkimer, Madison",
    Website: "https://mohawkvalley.score.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "SCORE chapter serving the Utica-Rome-Mohawk Valley area. Free mentoring with volunteer business veterans plus low-cost in-person workshops in Utica. Hosts joint events with thINCubator and the Greater Utica Chamber.",
  },
  {
    Resource: "Onondaga SBDC",
    Type: "Government",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Business counseling, loan packaging",
    CountiesServed: "Onondaga, Madison, Cortland, Cayuga, Oswego",
    Website: "https://www.onondagasbdc.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Small Business Development Center hosted at Onondaga Community College. Free 1:1 advising on business plans, financial projections, SBA loan packaging, and government contracting. Funded by the SBA and SUNY; serves five CNY counties.",
  },
  {
    Resource: "Mohawk Valley SBDC",
    Type: "Government",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Business counseling, Mohawk Valley",
    CountiesServed: "Oneida, Herkimer, Lewis",
    Website: "https://mvsbdc.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "SBDC hosted at SUNY Polytechnic Institute serving Oneida, Herkimer, and Lewis counties. Free advising on business formation, financing, government contracting, and exporting. Runs minority and veteran founder cohorts in partnership with EDGE.",
  },
  {
    Resource: "ESD Central New York Regional Office",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Central New York",
    FocusArea: "State grants, tax credits, capital programs",
    CountiesServed: "Onondaga, Madison, Oswego, Cortland, Cayuga",
    Website: "https://esd.ny.gov/regions/central-new-york",
    AverageCheckSize: "Varies",
    RelocationRequired: "No",
    About: "ESD's regional office staffing the Central New York REDC. Administers Excelsior Jobs tax credits, CNY Rising downtown revitalization grants, capital grants for shovel-ready projects, and Start-Up NY tax-free zone admission.",
  },
  {
    Resource: "ESD Mohawk Valley Regional Office",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Central New York",
    FocusArea: "State grants, workforce, semiconductor",
    CountiesServed: "Oneida, Herkimer",
    Website: "https://esd.ny.gov/regions/mohawk-valley",
    AverageCheckSize: "Varies",
    RelocationRequired: "No",
    About: "ESD's regional office for the Mohawk Valley REDC. Runs the MV500 talent attraction initiative, capital grants tied to the Wolfspeed semiconductor build-out, and ESD-funded workforce training. Founders apply through the annual CFA round.",
  },
  {
    Resource: "SBA Syracuse District Office",
    Type: "Government",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "SBA loans, federal contracting",
    CountiesServed: "34-county Upstate NY district",
    Website: "https://www.sba.gov/district/syracuse",
    AverageCheckSize: "$5K-$5M",
    RelocationRequired: "No",
    About: "Federal SBA office covering 34 Upstate NY counties from Syracuse. Founders get access to 7(a) and 504 loan guarantees, microloans, the SBIR/STTR pipeline, 8(a) certification, and HUBZone status. Hosts annual Small Business Week awards.",
  },
  {
    Resource: "Onondaga County IDA",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Central New York",
    FocusArea: "Industrial financing, PILOTs, bond issuance",
    CountiesServed: "Onondaga",
    Website: "https://www.ongoved.com",
    AverageCheckSize: "Varies",
    RelocationRequired: "No",
    About: "Onondaga County's Industrial Development Agency. Issues tax-exempt bonds, sales- and mortgage-tax exemptions, and PILOTs for capital projects. Active in the Micron-driven White Pine industrial corridor in Clay; founders use it for facility expansion financing.",
  },
  {
    Resource: "MV500",
    Type: "Government",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Talent attraction, Mohawk Valley relocation",
    CountiesServed: "Oneida, Herkimer",
    Website: "https://www.mv500.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Mohawk Valley regional talent-attraction campaign coordinated by ESD and EDGE. Founders relocating to Utica/Rome get concierge help with housing, schools, partner job placement, and intros to local business networks. Built around the Wolfspeed and Marcy Nanocenter expansion.",
  },
  {
    Resource: "Cortland County BDC/IDA",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Central New York",
    FocusArea: "Cortland County loans, IDA financing",
    CountiesServed: "Cortland",
    Website: "https://cortlandedge.com",
    AverageCheckSize: "$10K-$250K",
    RelocationRequired: "No",
    About: "Cortland County's Business Development Corporation and IDA. Offers low-interest loans, PILOT agreements, and brownfield site assistance. Manages the Cortland County Microenterprise Program for early-stage founders.",
  },
  {
    Resource: "WISE Women's Business Center",
    Type: "Mentorship",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Women founders, underrepresented entrepreneurs",
    CountiesServed: "Onondaga, Madison, Oswego, Cortland, Cayuga, Oneida, Herkimer",
    Website: "https://wisecenter.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "SBA-funded women's business center based at Syracuse University's Whitman School. Free 1:1 advising, the WISE Symposium annual conference, the StartFast for Women cohort, and certification help for WBE/MBE status. Programming aimed at women and BIPOC founders, open to all.",
  },
  {
    Resource: "SUNY EOC of Syracuse",
    Type: "Education",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Workforce training, adult education",
    CountiesServed: "Onondaga",
    Website: "https://eoc.syr.edu",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "SUNY Educational Opportunity Center in Syracuse offers free or low-cost vocational and small-business training for adults. Programs include culinary entrepreneurship, computer skills, and the Pathways to Apprenticeship track. Useful for founders building skilled hires.",
  },
  {
    Resource: "SUNY Oswego Center for Business and Community Development",
    Type: "Education",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Small business counseling, Oswego County",
    CountiesServed: "Oswego",
    Website: "https://www.oswego.edu/business/center-business-community-development",
    AverageCheckSize: "Cash prizes",
    RelocationRequired: "No",
    About: "SUNY Oswego center offering business consulting, market research, and the SBDC outreach office for Oswego County. Hosts the annual Compass Awards and the Oswego County Business Plan Competition with cash prizes.",
  },
  {
    Resource: "Cooperative Federal Credit Union",
    Type: "Funding",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Microloans, CDFI, underbanked founders",
    CountiesServed: "Onondaga",
    Website: "https://cooperativefederal.org",
    AverageCheckSize: "$1K-$50K",
    RelocationRequired: "No",
    About: "CDFI and member-owned credit union serving Syracuse. Offers small-business microloans, character-based lending, and free financial counseling for founders who don't qualify for conventional bank credit.",
  },
  {
    Resource: "Pathstone Enterprise Center",
    Type: "Funding",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Microloans, minority and women founders",
    CountiesServed: "Onondaga, Cayuga, Oswego, Western and Finger Lakes NY",
    Website: "https://pathstoneenterprisecenter.org",
    AverageCheckSize: "$1K-$50K",
    RelocationRequired: "No",
    About: "SBA-certified CDFI microlender serving Upstate NY. Loans from $1,000 to $50,000 for startups and growing small businesses paired with free 1:1 advising. Active focus on minority-, women-, and immigrant-owned ventures in the Syracuse and Auburn corridors.",
  },
  {
    Resource: "Mohawk Valley Small Business Revolving Loan Fund",
    Type: "Funding",
    Stage: "Early",
    Chapter: "Central New York",
    FocusArea: "Gap financing, small business loans",
    CountiesServed: "Oneida, Herkimer",
    Website: "https://mvedge.org/business-resources/financing/",
    AverageCheckSize: "$10K-$100K",
    RelocationRequired: "No",
    About: "Revolving loan fund administered by Mohawk Valley EDGE for Oneida and Herkimer county businesses. Provides gap financing, working capital, and equipment loans at below-market rates. Often used alongside SBA 504 or bank financing.",
  },
  {
    Resource: "FuzeHub — CNY",
    Type: "Government",
    Stage: "Growth",
    Chapter: "Central New York",
    FocusArea: "Manufacturing, hardware, tech commercialization",
    CountiesServed: "All CNY counties",
    Website: "https://fuzehub.com",
    AverageCheckSize: "$5K-$100K",
    RelocationRequired: "No",
    About: "Statewide NY MEP-affiliated nonprofit with active CNY presence. Hardware and manufacturing founders get connected to NY university labs and ESD-funded testing services. Operates the Jeff Lawrence Innovation Fund and Manufacturing Grants.",
  },
  {
    Resource: "Bond, Schoeneck & King — Emerging Companies",
    Type: "Legal",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Startup legal services, IP, venture financing",
    CountiesServed: "Onondaga, all CNY",
    Website: "https://www.bsk.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Syracuse-headquartered regional law firm with an established emerging-companies practice. Handles incorporation, equity grants, SAFEs, IP, and Series-stage venture financings. Frequent partner on Tech Garden and GENIUS NY founder events with discounted formation packages.",
  },
  {
    Resource: "Sync Coworking Syracuse",
    Type: "Coworking",
    Stage: "All",
    Chapter: "Central New York",
    FocusArea: "Coworking, private offices",
    CountiesServed: "Onondaga",
    Website: "https://www.synccoworking.com",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Independent coworking space in downtown Syracuse offering hot desks, dedicated desks, and private offices. Hosts founder meetups and informal mentor hours. Standard month-to-month memberships.",
  },
  {
    Resource: "On Point for College",
    Type: "Nonprofit",
    Stage: "Ideation",
    Chapter: "Central New York",
    FocusArea: "First-generation talent pipeline",
    CountiesServed: "Onondaga, Oneida, Madison",
    Website: "https://www.onpointforcollege.org",
    AverageCheckSize: "NA",
    RelocationRequired: "No",
    About: "Syracuse-based nonprofit getting first-generation students into and through college, with a growing career pathways arm. Useful to CNY founders building entry-level pipelines or apprenticeship programs in Syracuse, Utica, and Hamilton.",
  },
];

(async () => {
  console.log(`Seeding ${RESOURCES.length} resources (${RESOURCES.filter(r => r.Chapter === "Capital Region").length} Capital Region, ${RESOURCES.filter(r => r.Chapter === "Central New York").length} CNY)...`);

  const existingSnap = await db.collection("resources").get();
  const existing = new Set();
  existingSnap.forEach((doc) => {
    const d = doc.data();
    const name = (d.Resource || d.resource || "").trim().toLowerCase();
    const chapter = (d.Chapter || d.chapter || "").trim();
    if (name && chapter) existing.add(`${chapter}::${name}`);
  });

  let added = 0;
  let skipped = 0;
  const now = admin.firestore.FieldValue.serverTimestamp();

  for (const r of RESOURCES) {
    const key = `${r.Chapter}::${r.Resource.trim().toLowerCase()}`;
    if (existing.has(key)) {
      console.log(`  ↩︎  skip (exists): ${r.Chapter} — ${r.Resource}`);
      skipped++;
      continue;
    }
    await db.collection("resources").add({
      ...r,
      createdAt: now,
      updatedAt: now,
    });
    console.log(`  ✓  added: ${r.Chapter} — ${r.Resource}`);
    added++;
  }

  console.log(`\nDone. Added ${added}, skipped ${skipped} (already present).`);
  process.exit(0);
})().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
